### ISSUE TITLE
kubeflow-install.sh does not complete successfully

### ISSUE THREAD

**Issue by bjcmit** [kaizentm/kubemlops#51]
When I run kubeflow-install.sh, I get the following output:

![image](https://user-images.githubusercontent.com/14097253/85596699-d0f10b00-b5fe-11ea-9e3a-f38f3ce8b476.png)

The problem seems to be with carriage returns (i.e. '\r'). The following were unsuccessful at fixing the issue:

- dos2unix kubeflow-install.sh
- sed -i '1s/\r//' kubeflow-install.sh

**Comment by bjcmit** [comment]
ghcreds-secrets.sh seems to have a similar issue because I get the following output when I run it:

Error from server (NotFound): namespaces "\r" not found

**Comment by bjcmit** [comment]
kubemlopsbot.sh also seems to have a similar issue. Here is the output when I run it:

Error from server (NotFound): error when creating "kubemlopsbot.yml": namespaces "\r" not found
Error from server (NotFound): error when creating "kubemlopsbot.yml": namespaces "\r" not found

**Comment by eedorenko** [comment]
Just ran kubeflow-install.sh on Mac OS X and Ubuntu Linux. Works like a charm. Don't have Windows.
Did you modify (intentionally or unintentionally) the files on windows? Normally, "\r" symbols are added if you update the files on Windows as it has CRLF End-of-Line sequence.    
Furthermore, these scripts are used by IaC.yaml pipeline and it works.

**Comment by bjcmit** [comment]
I am running on Ubuntu Linux and I just did a git clone.

**Comment by tcare** [comment]
Closing for now, let me know if you still run into it.
