### ISSUE TITLE
azure-credentials.sh does not complete successfully

### ISSUE THREAD

**Issue by bjcmit** [kaizentm/kubemlops#52]
When I run azure-credentials.sh, I get the following output:

![image](https://user-images.githubusercontent.com/14097253/85598046-0ea26380-b600-11ea-81d1-6557d810610f.png)

This seems to be unrelated to the kubeflow-install.sh issue, and seems to be related to a change in kubectl.

**Comment by eedorenko** [comment]
Did you initialize $AZ_SUBSCRIPTION_ID, $AZ_TENANT_ID, ... variables before running the script?

**Comment by eedorenko** [comment]
The script is used by IaC.yaml pipeline

**Comment by bjcmit** [comment]
I did not initialize  $AZ_SUBSCRIPTION_ID, $AZ_TENANT_ID, ... variables before running the script. This needs to be added to the instructions.
