### ISSUE TITLE
attach-acr.sh does not complete successfully

### ISSUE THREAD

**Issue by bjcmit** [kaizentm/kubemlops#53]
When I run attach-acr.sh, I get the following output:

az aks update: error: argument --name/-n: expected one argument
usage: az aks update [-h] [--verbose] [--debug] [--only-show-errors]
                     [--output {json,jsonc,yaml,yamlc,table,tsv,none}]
                     [--query JMESPATH] [--subscription _SUBSCRIPTION]
                     --resource-group RESOURCE_GROUP_NAME --name NAME
                     [--enable-cluster-autoscaler]
                     [--disable-cluster-autoscaler]
                     [--update-cluster-autoscaler] [--min-count MIN_COUNT]
                     [--max-count MAX_COUNT] [--uptime-sla]
                     [--load-balancer-managed-outbound-ip-count LOAD_BALANCER_MANAGED_OUTBOUND_IP_COUNT]
                     [--load-balancer-outbound-ips LOAD_BALANCER_OUTBOUND_IPS]
                     [--load-balancer-outbound-ip-prefixes LOAD_BALANCER_OUTBOUND_IP_PREFIXES]
                     [--load-balancer-outbound-ports LOAD_BALANCER_OUTBOUND_PORTS]
                     [--load-balancer-idle-timeout LOAD_BALANCER_IDLE_TIMEOUT]
                     [--attach-acr ACR_NAME_OR_RESOURCE_ID]
                     [--detach-acr ACR_NAME_OR_RESOURCE_ID]
                     [--api-server-authorized-ip-ranges API_SERVER_AUTHORIZED_IP_RANGES]

**Comment by eedorenko** [comment]
Did you initialize $AKS_NAME, $RESOURCE_GROUP, $ACR_NAME variables before running the script?

**Comment by bjcmit** [comment]
I did not  initialize $AKS_NAME, $RESOURCE_GROUP, $ACR_NAME variables before running the script. This should be added to the instructions.
